sourcegraph/sourcegraph-typescript

- extension/src/extension.ts
- package.json
- server/src/dependencies.ts
- server/src/graphql.ts
- server/src/server.ts
- yarn.lock
> Rewrite node_modules URIs

- extension/src/lsp-conversion.ts
A nonnegative hover priority takes precedence over all negative hover priorities, so this means if there is a lang-typescript hover, the basic-code-intel hover will not show. Note that hover priorities will be removed in 3.0 (in https://github.com/sourcegraph/sourcegraph/pull/2039); this fix is only helpful for 3.0 beta.
fix https://github.com/sourcegraph/sourcegraph/issues/1938
> fix: omit multiple hovers when using with basic-code-intel

- extension/src/extension.ts
- package.json
- yarn.lock
This uses the [@sourcegraph/basic-code-intel](https://www.npmjs.com/package/@sourcegraph/basic-code-intel) library to provide code intelligence powered by ctags + search when the serverUrl is not yet set.
There could probably be better messaging around this (e.g. a message in the console).
> Fall back to basic-code-intel when typescript.serverUrl is not set

- package.json
If this configuration value is not set, the extension falls back to fuzzy mode. It not being set is not an error.
> make typescript.serverUrl optional

- server/src/server.ts
Fix https://github.com/sourcegraph/sourcegraph/issues/2451 (see that issue for context).
> Update progress message to "Loading TypeScript project"

- extension/src/extension.ts
`registerImplementationProvider` is deprecated and is being removed in 3.2 (see https://github.com/sourcegraph/sourcegraph/pull/1697). This uses the new registerLocationProvider.
(See the note on backcompat for why it needs to also keep the call to `registerImplementationProvider` for now.)
Related to (but does not depend on) https://github.com/sourcegraph/sourcegraph/pull/2733
> use registerLocationProvider for impls, remove deprecated registerImplementationProvider

- package.json
The "References: Search mode" action was showing up on other panels, such as Git history and (if enabled) code discussions. This makes it so they only show up on the appropriate panels.
Related: https://github.com/sourcegraph/sourcegraph-go/pull/48
> hide panel/toolbar action "References: Search mode" on irrelevant panels

- extension/src/dependencies.ts
If a JavaScript or TypeScript file has no ancestor package.json, the extension will enter an infinite loop requesting `http://localhost:3080/package.json` (where `http://localhost:3080` is the Sourcegraph URL). This means hundreds/thousands of requests within just a few seconds after loading. This occurs because it gets into a situation where `parent.href` and `rootUri.href` are both `http://localhost:3080/`, so the loop while-condition is always true, and subsequent iterations don't change the value of `parent.href`.
Repro at http://localhost:3080/github.com/Microsoft/TypeScriptSamples/-/blob/interfaces/interfaces.ts#L11:22&tab=references (with the TypeScript language server enabled and that repository added). I was unable to reproduce this at …
> fix infinite loop when file lacks ancestor package.json

- server/src/resources.ts
Previous to this change, `walkUp` would only walk up 1 directory level and stop.
> Fix walkUp

- server/src/server.ts
Some repositories check in `node_modules/`, which is often times massive and not worth analyzing.
@felixfbecker If the problem is clear, can you take this from here?
See https://github.com/sourcegraph/sourcegraph/issues/2683
> Skip node_modules

- extension/src/extension.ts
- package.json
- yarn.lock
This scans the file for `import`s or `require`s and filters definitions to ones that are defined in one of the imported files. If none match, the constraint is lifted.
Corresponds to https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/77
> Filter definitions by imports in basic-code-intel mode

- extension/src/extension.ts
- package.json
- yarn.lock
Context: https://github.com/sourcegraph/sourcegraph-typescript/pull/139#discussion_r269244637
I did not get any errors with using `import * as path from 'path'`. Using `require()` makes every interaction with `path` not type safe because it is type `any`.
> Remove path-browserify

- README.md
The `replicas` key was in the wrong spot.
> Fix k8s config

- extension/src/extension.ts
- package.json
- yarn.lock
See https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/100
> Add button to submit feedback

- README.md
The `namespace: prod` is an artifact specific to our k8s config for sourcegraph.com and doesn't hold in general for customers.
> remove `namespace: prod`

- extension/src/basic-code-intel.ts
- extension/src/extension.ts
- package.json
- yarn.lock
Resolves https://github.com/sourcegraph/sourcegraph/issues/5008
This adds LSIF support to the TypeScript extension. Here's the behavior:
- When `codeIntel.lsif` is `true`: use LSIF but fall back to basic-code-intel when LSIF data doesn't exist
- Otherwise when `typescript.serverUrl` is not set: only use basic-code-intel
- Otherwise `typescript.serverUrl` must be set, so use the language server
Due to the amount of time it would take to implement and considering that we're migrating away from language servers (see the [roadmap](https://docs.google.com/document/d/1JAbq58Tp-3R2oahkYB9fnHBjlOTSqEEmrp8T66tmHfQ/edit#heading=h.r6zmhuup0vm3)), this isn't quite the same as the other language extensions, which fall back in this order: 1. LSIF 2. language server 3. basic-code-intel
> Add LSIF support

- extension/src/extension.ts
The problem seems to be that the Observable returned by `provideDefinition` and wrapped by `distinctUntilChanged` is hot, was emitting exactly once, and was emitting before the Sourcegraph extension API called `provideDefinition` a second time. On the second call, `distinctUntilChanged` returned the cached Observable which was done emitting and ended up preventing any location results from getting to the Sourcegraph extension API.
It seems as though https://github.com/sourcegraph/sourcegraph/issues/1321 is either not actually fixed, or the double-call has reappeared.
Fixes https://github.com/sourcegraph/sourcegraph/issues/5620
cc @sourcegraph/code-intel
> Fix basic code intel definitions

- package.json
Mirrors https://github.com/sourcegraph/sourcegraph-typescript/commit/80a9112705d8caa6ebfc01c2ede44341c33b6c97#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L173-R173
> Fix package.json serve-ext

- package.json
- src/extension/extension.ts
- yarn.lock
This pulls in https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/179 for fallback because LSIF data might be sparse.
For references: if LSP is enabled, then use that exclusively.
> Fallback from LSIF to others

- package.json
- src/extension/extension.ts
- yarn.lock
Add precision indication badges in def/ref/hover results.
> Add badges.

- src/extension/extension.ts
Basic code intel was changed to use either the GraphQL API (when available) or the HTTP API (as a fallback). The HTTP API has been deprecated and removed as of 3.12.
This change did not update the behavior of mkIsLSIFAvailable, which this repository used in an unexpected way. The isLSIFAvailable will therefore only check the existence of LSIF data via the HTTP API, which will now return 404 on all requests.
This PR removes it from the path of defs/refs/hovers, as these methods now check for existence before querying internally.
> Do not block LSIF definition/hovers with isLSIFAvailable.
